version: '3'

networks:
  minharede:
    driver: bridge
    
services:
  db:
    image: mysql:5.7
    container_name: 'mysql_database'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - minharede
    ports:
      - "3306:3306"
    volumes:
      - ./backend/db/db.sql:/docker-entrypoint-initdb.d/db.sql
    command: --init-file /docker-entrypoint-initdb.d/db.sql
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
  backend:
    build: ./backend
    networks:
      - minharede
    ports:
      - "5000:5000"
    depends_on:
      - db

