version: '3'
services:
  db:
    image: mysql
    container_name: 'mysql_database'
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./backend/db/db.sql:/docker-entrypoint-initdb.d/db.sql
    command: --init-file /docker-entrypoint-initdb.d/db.sql
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db

